### ISSUE TITLE
Wiring Diagrams / Schematic

### ISSUE THREAD

**Issue by LoneWalkerWolf** [expanseElectronics/ethernetNodes#4]
Can you tell me the gpio wiring diagram

_Originally posted by @mingdamedia in https://github.com/expanseElectronics/ethernetNodes/issues/3#issuecomment-1657003575_

Moving this to new issue as OP keeps commenting on unrelated issues. 

ESP8266 GPIO pinout is as follows:
RST - To reset button with 3.3K pullup resistor. 
ADC - NC
EN - 3.3V
IO16 - MAX485 RE# and DE pin. (ensure correct logic level)
IO14 - W5500 SCLK
IO12 - W5500 MISO
1013  -W5500 MOSI
VCC - 3.3V
TXD - TX and MAX485 DI. (ensure correct logic level)
RDX - RX and MAX485 RO.  (ensure correct logic level)
IO5 - W5500 RESET (ensure no clash with SPI)
IO4 - WS2812B LEDs 
IO0 - Pulled to 3.3V with 3.3K resistor.
IO2 - MAX485 (port 2) DI. (ensure correct logic level)
IO15 - W5500 SCS (ensure no clash with SPI)
GND - GND

Hope this helps.

**Comment by mingdamedia** [comment]
Can you add two more dmx outputs？

**Comment by MicroMarty** [comment]
Are you using a buffer on gpio15, like that ?
https://esp8266hints.wordpress.com/2018/02/13/adding-an-ethernet-port-to-your-esp-revisited/

Or did you use another method?

**Comment by LoneWalkerWolf** [comment]
@MicroMarty Yes, we're using a buffer. Pretty much exactly like the one you've linked. 

![image](https://github.com/expanseElectronics/ethernetNodes/assets/63847434/fd40b930-0fca-41a7-8908-c97e0defcbc7)

**Comment by LoneWalkerWolf** [comment]
> Can you add two more dmx outputs？

We are working on this. Currently we are working on making a DMX splitter with a built in DMX node. We will let you know when we have added four DMX ports.

**Comment by MicroMarty** [comment]
Hi,

What is the process for resetting the node configuration?

The reset pin connect to ground with a 3k3 resistor give me just a reboot.

Only the 5 reboot method reset the configuration.


Thank again for you great work!

**Comment by LoneWalkerWolf** [comment]
Closed due to inactivity.

**Comment by mrv96** [comment]
Looking at the code, it seems that `IO0` is also connected to MAX485 (port 2) RE# and DE pin.
