### ISSUE TITLE
Factory reset button not working

### ISSUE THREAD

**Issue by MicroMarty** [expanseElectronics/ethernetNodes#7]
Hi

The button attached to RST pin doesn't factory reset the parameters when it's pressed during boot.

Only the 5 reboot method works.

Thx

**Comment by LoneWalkerWolf** [comment]
Yes, that is intended, the RST button just resets the microcontroller. It shouldn't factory reset the parameters. 

There is an option for adding an extra button, to factory reset, but this requires a modification to the code to allow the button to be used this way.
